
package protest2;

import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.io.FileInputStream;
import java.io.InputStream;
import javax.swing.JFrame;
import javax.swing.Timer;
import static protest2.Home.audioStream;
import static protest2.Home.bgPlay;
import sun.audio.AudioPlayer;
import sun.audio.AudioStream;

/**
 *
 * @author Uttam
 */
public class DragonsArt extends javax.swing.JFrame {

    
    Home homeRef;
    static boolean creditFlag;
    public DragonsArt() {
        initComponents();
        setExtendedState(JFrame.MAXIMIZED_BOTH);
        dispose();
        setUndecorated(true);
    }
    
    public DragonsArt(Home home) {
        initComponents();
        setExtendedState(JFrame.MAXIMIZED_BOTH);
        dispose();
        setUndecorated(true);
        homeRef=home;
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        back = new javax.swing.JButton();
        dragon1 = new javax.swing.JLabel();
        dragon3 = new javax.swing.JLabel();
        dragon4 = new javax.swing.JLabel();
        dragon6 = new javax.swing.JLabel();
        dragon12 = new javax.swing.JLabel();
        dragon16 = new javax.swing.JLabel();
        dragon15 = new javax.swing.JLabel();
        dragon19 = new javax.swing.JLabel();
        dragon8 = new javax.swing.JLabel();
        dragon18 = new javax.swing.JLabel();
        dragon10 = new javax.swing.JLabel();
        dragon9 = new javax.swing.JLabel();
        background = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMinimumSize(new java.awt.Dimension(1366, 760));
        getContentPane().setLayout(null);

        back.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/backbutt.png"))); // NOI18N
        back.setText("back");
        back.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        back.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                backActionPerformed(evt);
            }
        });
        getContentPane().add(back);
        back.setBounds(1250, 0, 120, 40);

        dragon1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/dragon13.gif"))); // NOI18N
        getContentPane().add(dragon1);
        dragon1.setBounds(-10, 640, 140, 110);

        dragon3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/dragon20.gif"))); // NOI18N
        getContentPane().add(dragon3);
        dragon3.setBounds(380, 610, 150, 130);

        dragon4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/dragon6.gif"))); // NOI18N
        getContentPane().add(dragon4);
        dragon4.setBounds(80, 110, 193, 190);

        dragon6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/dragon17.gif"))); // NOI18N
        getContentPane().add(dragon6);
        dragon6.setBounds(320, -20, 260, 210);

        dragon12.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/dragon29.gif"))); // NOI18N
        getContentPane().add(dragon12);
        dragon12.setBounds(1200, 150, 140, 170);

        dragon16.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/dragon36.gif"))); // NOI18N
        getContentPane().add(dragon16);
        dragon16.setBounds(350, 310, 560, 370);

        dragon15.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/dragon45.gif"))); // NOI18N
        getContentPane().add(dragon15);
        dragon15.setBounds(830, 620, 160, 100);

        dragon19.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/dragon33.gif"))); // NOI18N
        getContentPane().add(dragon19);
        dragon19.setBounds(860, 360, 730, 290);

        dragon8.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/dragon19.gif"))); // NOI18N
        getContentPane().add(dragon8);
        dragon8.setBounds(200, 600, 130, 100);

        dragon18.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/dragon32.gif"))); // NOI18N
        getContentPane().add(dragon18);
        dragon18.setBounds(-130, 220, 580, 480);

        dragon10.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/dragon23.gif"))); // NOI18N
        getContentPane().add(dragon10);
        dragon10.setBounds(350, 520, 170, 100);

        dragon9.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/littleDragon.gif"))); // NOI18N
        getContentPane().add(dragon9);
        dragon9.setBounds(880, 90, 150, 210);

        background.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/dragonArtBG.jpg"))); // NOI18N
        background.setText("jLabel1");
        getContentPane().add(background);
        background.setBounds(0, -20, 1370, 830);

        pack();
    }// </editor-fold>//GEN-END:initComponents
    public static void menuSound(){
        
        try{
            String gongFile = "src/sounds/menu.wav";
            InputStream in = new FileInputStream(gongFile);
            AudioStream audioStream = new AudioStream(in);
            AudioPlayer.player.start(audioStream);
            
        }catch(Exception e){
            //System.out.println(e);
            
        }
        
    }
    
    void backButton(){
        this.dispose();
    }
    
    
    private void backActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_backActionPerformed
        menuSound();
        backButton();

    }//GEN-LAST:event_backActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(DragonsArt.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(DragonsArt.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(DragonsArt.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(DragonsArt.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new DragonsArt().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton back;
    private javax.swing.JLabel background;
    private javax.swing.JLabel dragon1;
    private javax.swing.JLabel dragon10;
    private javax.swing.JLabel dragon12;
    private javax.swing.JLabel dragon15;
    private javax.swing.JLabel dragon16;
    private javax.swing.JLabel dragon18;
    private javax.swing.JLabel dragon19;
    private javax.swing.JLabel dragon3;
    private javax.swing.JLabel dragon4;
    private javax.swing.JLabel dragon6;
    private javax.swing.JLabel dragon8;
    private javax.swing.JLabel dragon9;
    // End of variables declaration//GEN-END:variables
}
