
package protest2;

import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.io.FileInputStream;
import java.io.InputStream;
import javax.swing.JFrame;
import javax.swing.Timer;
import static protest2.Home.audioStream;
import static protest2.Home.bgPlay;
import sun.audio.AudioPlayer;
import sun.audio.AudioStream;

/**
 *
 * @author Uttam
 */
public class OptionsWindow extends javax.swing.JFrame {

    
    Home homeRef;
    static boolean creditFlag;
    public OptionsWindow() {
        initComponents();
        creditPanel.setVisible(false);
        setExtendedState(JFrame.MAXIMIZED_BOTH);
    }
    
    public OptionsWindow(Home home) {
        initComponents();
        setExtendedState(JFrame.MAXIMIZED_BOTH);
        homeRef=home;
        creditFlag=false;
        if(!bgPlay){
            music.setIcon(new javax.swing.ImageIcon("src\\Images\\off.png"));
            
        }
        else{
            music.setIcon(new javax.swing.ImageIcon("src\\Images\\on.png"));
        }
        creditPanel.setVisible(false);
        animation.setVisible(false);
        animation.doClick();
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        back = new javax.swing.JButton();
        OptionsText = new javax.swing.JLabel();
        animation = new javax.swing.JButton();
        creditButton = new javax.swing.JButton();
        music = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        musicButton = new javax.swing.JButton();
        dragonArts = new javax.swing.JButton();
        jLabel10 = new javax.swing.JLabel();
        creditPanel = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMaximumSize(new java.awt.Dimension(1366, 760));
        setMinimumSize(new java.awt.Dimension(1366, 760));
        getContentPane().setLayout(null);

        back.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/backbutt.png"))); // NOI18N
        back.setText("back");
        back.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        back.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                backActionPerformed(evt);
            }
        });
        getContentPane().add(back);
        back.setBounds(-100, 0, 280, 60);

        OptionsText.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/CreditsText.png"))); // NOI18N
        getContentPane().add(OptionsText);
        OptionsText.setBounds(510, 10, 343, 130);

        animation.setText("AnimButt");
        animation.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                animationActionPerformed(evt);
            }
        });
        getContentPane().add(animation);
        animation.setBounds(260, 80, 90, 23);

        creditButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/showCredit.png"))); // NOI18N
        creditButton.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        creditButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                creditButtonActionPerformed(evt);
            }
        });
        getContentPane().add(creditButton);
        creditButton.setBounds(350, 230, 260, 50);

        music.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/on.png"))); // NOI18N
        music.setToolTipText("Play/Stop Backgroud Music");
        music.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        music.setBorderPainted(false);
        music.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        music.setFocusPainted(false);
        music.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                musicMouseClicked(evt);
            }
        });
        music.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                musicActionPerformed(evt);
            }
        });
        getContentPane().add(music);
        music.setBounds(120, 230, 160, 270);

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 36)); // NOI18N
        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/arrow1.png"))); // NOI18N
        getContentPane().add(jLabel3);
        jLabel3.setBounds(560, 230, 110, 50);

        musicButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/musicOptions.png"))); // NOI18N
        musicButton.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        musicButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                musicButtonActionPerformed(evt);
            }
        });
        getContentPane().add(musicButton);
        musicButton.setBounds(350, 450, 260, 50);

        dragonArts.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/dragonArts.png"))); // NOI18N
        dragonArts.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        dragonArts.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                dragonArtsActionPerformed(evt);
            }
        });
        getContentPane().add(dragonArts);
        dragonArts.setBounds(350, 340, 260, 50);

        jLabel10.setFont(new java.awt.Font("Tahoma", 1, 36)); // NOI18N
        jLabel10.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/arrow.png"))); // NOI18N
        getContentPane().add(jLabel10);
        jLabel10.setBounds(290, 450, 120, 50);

        creditPanel.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/optionsCredit.png"))); // NOI18N
        creditPanel.setText("jLabel11");
        getContentPane().add(creditPanel);
        creditPanel.setBounds(680, 230, 550, 330);

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/optionsBG.jpg"))); // NOI18N
        jLabel1.setText("jLabel1");
        getContentPane().add(jLabel1);
        jLabel1.setBounds(0, 0, 1380, 760);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void backActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_backActionPerformed
        // TODO add your handling code here:
        menuSound();
        backButton();
        
    }//GEN-LAST:event_backActionPerformed
    public static void menuSound(){
        
        try{
            String gongFile = "src/sounds/menu.wav";
            InputStream in = new FileInputStream(gongFile);
            AudioStream audioStream = new AudioStream(in);
            AudioPlayer.player.start(audioStream);
            
        }catch(Exception e){
            //System.out.println(e);
            
        }
        
    }
    
    void backButton(){
        homeRef.show();
        this.dispose();
    }
    
    Timer timer;
    
    int xOptionsText=500;
    int yOptionsText=-100;
    int wOptionsText=440;
    int hOptionsText=140;
    
    private void animationActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_animationActionPerformed
        // TODO add your handling code here:
        timer = new Timer(10, new ActionListener() {
      @Override
      public void actionPerformed(ActionEvent e) {
           
        if(yOptionsText<10){
            yOptionsText+=5;
            OptionsText.setBounds(xOptionsText, yOptionsText, wOptionsText, hOptionsText);
        }
        else {
            yOptionsText=-100;
            ((Timer) (e.getSource())).stop();
        }
      }
    });
      
    timer.setInitialDelay(0);
    timer.start();
        
    }//GEN-LAST:event_animationActionPerformed
    
    private void creditButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_creditButtonActionPerformed
        // TODO add your handling code here:
        if(!creditFlag){
            creditPanel.setVisible(true); 
            creditButton.setIcon(new javax.swing.ImageIcon("src\\Images\\hideCredit.png"));
            creditFlag=true;
        }  
        else{
            creditPanel.setVisible(false);
            creditButton.setIcon(new javax.swing.ImageIcon("src\\Images\\showCredit.png"));
            creditFlag=false;
        }
        
    }//GEN-LAST:event_creditButtonActionPerformed

    private void musicMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_musicMouseClicked

    }//GEN-LAST:event_musicMouseClicked

    private void musicActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_musicActionPerformed

        try{
            if(homeRef.bgPlay){
                AudioPlayer.player.stop(homeRef.audioStream);
                homeRef.audioStream.close();
                homeRef.bgPlay=false;
                music.setIcon(new javax.swing.ImageIcon("src\\Images\\off.png"));
            }
            else{
                
                InputStream in = new FileInputStream(homeRef.gongFile);
                homeRef.audioStream = new AudioStream(in);
                AudioPlayer.player.start(homeRef.audioStream);
                homeRef.bgPlay=true;
                music.setIcon(new javax.swing.ImageIcon("src\\Images\\on.png"));
            }
        }catch(Exception e){

        }

    }//GEN-LAST:event_musicActionPerformed

    private void musicButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_musicButtonActionPerformed
        // TODO add your handling code here:
        music.doClick();
    }//GEN-LAST:event_musicButtonActionPerformed

    private void dragonArtsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_dragonArtsActionPerformed
        // TODO add your handling code here:
        new DragonsArt().show();
    }//GEN-LAST:event_dragonArtsActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(OptionsWindow.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(OptionsWindow.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(OptionsWindow.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(OptionsWindow.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new OptionsWindow().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel OptionsText;
    private javax.swing.JButton animation;
    private javax.swing.JButton back;
    private javax.swing.JButton creditButton;
    private javax.swing.JLabel creditPanel;
    private javax.swing.JButton dragonArts;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JButton music;
    private javax.swing.JButton musicButton;
    // End of variables declaration//GEN-END:variables
}
