
package protest2;

import java.awt.Color;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.awt.event.KeyEvent;
import javax.swing.AbstractAction;
import javax.swing.ActionMap;
import javax.swing.InputMap;
import javax.swing.JComponent;
import javax.swing.KeyStroke;
import javax.swing.Timer;

/**
 *
 * @author Uttam
 */
public class LoseDialog extends javax.swing.JDialog {

    /**
     * A return status code - returned if Cancel button has been pressed
     */
    public static final int RET_CANCEL = 0;
    /**
     * A return status code - returned if OK button has been pressed
     */
    public static final int RET_OK = 1;

    /**
     * Creates new form LoseDialog
     */
    
    public LoseDialog(java.awt.Frame parent, boolean modal) {
        
        super(parent, modal);
        initComponents();
        
        

        // Close the dialog when Esc is pressed
        String cancelName = "cancel";
        InputMap inputMap = getRootPane().getInputMap(JComponent.WHEN_ANCESTOR_OF_FOCUSED_COMPONENT);
        inputMap.put(KeyStroke.getKeyStroke(KeyEvent.VK_ESCAPE, 0), cancelName);
        ActionMap actionMap = getRootPane().getActionMap();
        actionMap.put(cancelName, new AbstractAction() {
            public void actionPerformed(ActionEvent e) {
                doClose(RET_CANCEL);
            }
        });
    }
    
    
    ExtremeGame temp;
    public LoseDialog(java.awt.Frame parent,ExtremeGame ref, boolean modal,String reason) {
        
        super(parent, modal);
        initComponents();
        temp=ref;
        tButt.setVisible(false);
        tButt.doClick();
        if("ZeroGuesses".equals(reason))
            reason="                                No Guesses Left!!";
        else
            reason="                                Oops!! Time's Up!";
        
        temp.revealWord(reason);
        ReasonText.setText(reason);
        
        String cancelName = "cancel";
        InputMap inputMap = getRootPane().getInputMap(JComponent.WHEN_ANCESTOR_OF_FOCUSED_COMPONENT);
        inputMap.put(KeyStroke.getKeyStroke(KeyEvent.VK_ESCAPE, 0), cancelName);
        ActionMap actionMap = getRootPane().getActionMap();
        actionMap.put(cancelName, new AbstractAction() {
            public void actionPerformed(ActionEvent e) {
                doClose(RET_CANCEL);
            }
        });
    }

    /**
     * @return the return status of this dialog - one of RET_OK or RET_CANCEL
     */
    public int getReturnStatus() {
        return returnStatus;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        okButton = new javax.swing.JButton();
        cancelButton = new javax.swing.JButton();
        tButt = new javax.swing.JButton();
        pandaSoul = new javax.swing.JLabel();
        ReasonText = new javax.swing.JTextField();
        BackImage = new javax.swing.JLabel();

        setBounds(new java.awt.Rectangle(350, 250, 600, 450));
        setLocation(new java.awt.Point(350, 200));
        setMaximumSize(new java.awt.Dimension(640, 440));
        setMinimumSize(new java.awt.Dimension(640, 430));
        setPreferredSize(new java.awt.Dimension(650, 400));
        setResizable(false);
        setType(java.awt.Window.Type.POPUP);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowClosing(java.awt.event.WindowEvent evt) {
                closeDialog(evt);
            }
        });
        getContentPane().setLayout(null);

        okButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/LoseQuit.png"))); // NOI18N
        okButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                okButtonActionPerformed(evt);
            }
        });
        getContentPane().add(okButton);
        okButton.setBounds(20, 300, 160, 70);
        getRootPane().setDefaultButton(okButton);

        cancelButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/LosePlayAgain.png"))); // NOI18N
        cancelButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cancelButtonActionPerformed(evt);
            }
        });
        getContentPane().add(cancelButton);
        cancelButton.setBounds(470, 300, 160, 70);

        tButt.setText("tButt");
        tButt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tButtActionPerformed(evt);
            }
        });
        getContentPane().add(tButt);
        tButt.setBounds(260, 370, 110, 23);

        pandaSoul.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/soul2.png"))); // NOI18N
        getContentPane().add(pandaSoul);
        pandaSoul.setBounds(180, 230, 280, 160);

        ReasonText.setEditable(false);
        ReasonText.setBackground(new java.awt.Color(140, 0, 0));
        ReasonText.setFont(new java.awt.Font("Trebuchet MS", 3, 24)); // NOI18N
        ReasonText.setForeground(new java.awt.Color(255, 255, 255));
        ReasonText.setText("                                       Reason");
        ReasonText.setBorder(null);
        ReasonText.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ReasonTextActionPerformed(evt);
            }
        });
        getContentPane().add(ReasonText);
        ReasonText.setBounds(0, 160, 650, 60);

        BackImage.setIcon(new javax.swing.ImageIcon("E:\\project\\project\\Images\\png\\LoseDialog.png")); // NOI18N
        BackImage.setMaximumSize(new java.awt.Dimension(700, 450));
        BackImage.setMinimumSize(new java.awt.Dimension(700, 450));
        getContentPane().add(BackImage);
        BackImage.setBounds(0, 0, 652, 401);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void okButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_okButtonActionPerformed
        
        doClose(RET_OK);
        temp.anotherGame();
    }//GEN-LAST:event_okButtonActionPerformed

    private void cancelButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cancelButtonActionPerformed
        doClose(RET_CANCEL);
        temp.backButton();
        temp.dispose();
        this.dispose();
        
    }//GEN-LAST:event_cancelButtonActionPerformed

    /**
     * Closes the dialog
     */
    private void closeDialog(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_closeDialog
        doClose(RET_CANCEL);
        temp.backButton();
        temp.dispose();
        this.dispose();
    }//GEN-LAST:event_closeDialog

    Timer timer;
    int xSoul=180;
    int ySoul=230;
    int wSoul=280;
    int hSoul=160;
    
    private void tButtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tButtActionPerformed
        // TODO add your handling code here:
      timer = new Timer(50, new ActionListener() {
      @Override
      public void actionPerformed(ActionEvent e) {
        
        if(ySoul>-200){
               ySoul=ySoul-2;
               pandaSoul.setBounds(xSoul, ySoul, wSoul, hSoul);
        }
        else{
            //pandaSoul.setVisible(false);
            ((Timer) (e.getSource())).stop();
            xSoul=180;
            ySoul=230;
            wSoul=280;
            hSoul=160;
        }
      }
    });
      
    timer.setInitialDelay(0);
    timer.start();
    
    }//GEN-LAST:event_tButtActionPerformed

    private void ReasonTextActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ReasonTextActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_ReasonTextActionPerformed
    
    private void doClose(int retStatus) {
        returnStatus = retStatus;
        setVisible(false);
        dispose();
    }

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(LoseDialog.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(LoseDialog.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(LoseDialog.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(LoseDialog.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                LoseDialog dialog = new LoseDialog(new javax.swing.JFrame(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel BackImage;
    private javax.swing.JTextField ReasonText;
    private javax.swing.JButton cancelButton;
    private javax.swing.JButton okButton;
    private javax.swing.JLabel pandaSoul;
    private javax.swing.JButton tButt;
    // End of variables declaration//GEN-END:variables

    private int returnStatus = RET_CANCEL;
}
